plugins { id 'com.android.application' }
android {
    namespace 'fi.varjoaika.widget'
    compileSdk 36
    defaultConfig {
        applicationId 'fi.varjoaika.android'
        minSdk 21
        targetSdk 36
        versionCode 101
        versionName '1.0.1'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
dependencies {
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test:rules:1.6.1'
}
